### ISSUE TITLE
Fail to make jetbot_navigation

### ISSUE THREAD

**Issue by jc-bao** [issaiass/jetbot_diff_drive#3]
When I tried to make jetbot_navigation package,an error occures:
`-- +++ processing catkin package: 'jetbot_navigation'
-- ==> add_subdirectory(jetbot_navigation)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
CMake Error at jetbot_navigation/CMakeLists.txt:13 (roslaunch_add_file_check):
  Unknown CMake command "roslaunch_add_file_check".

-- Configuring incomplete, errors occurred!
See also "/Users/reedpan/Seafile/ReedPan/College/Research/RE_ROS/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/Users/reedpan/Seafile/ReedPan/College/Research/RE_ROS/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed`

I think it is launch file's issue.
by adding `roslaunch` to `find_package`, the problem was sloved.
`
find_package(catkin REQUIRED COMPONENTS
  roslaunch
  amcl
  jetbot_viz
  map_server
  move_base
)
`

**Comment by issaiass** [comment]
I think is not a launch file issue because i have a video of everything that i code or post on github.

Considering the change is simple i will post your request as a improvement of the repo today or tomorrow at the end of the day.

Thanks for your reviews for improving the repository.
