### ISSUE TITLE
Could NOT find jetbot_viz (missing: jetbot_viz_DIR)

### ISSUE THREAD

**Issue by asps946701** [issaiass/jetbot_diff_drive#4]
Hi , when catkin "jetbot_navigation"  i got "Could NOT find jetbot_viz" error
How can solution this problem , Thanks!

---------------Version information----------------
-I use waveshare jetbot image 18.04 upgrade to 20.04 
-ROS version : noetic
-opencv 4.2.0 
-python 3.8.10
-------------------  error massage---------------------

-- Could NOT find jetbot_viz (missing: jetbot_viz_DIR)
-- Could not find the required component 'jetbot_viz'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "jetbot_viz" with
  any of the following names:

    jetbot_vizConfig.cmake
    jetbot_viz-config.cmake

  Add the installation prefix of "jetbot_viz" to CMAKE_PREFIX_PATH or set
  "jetbot_viz_DIR" to a directory containing one of the above files.  If
  "jetbot_viz" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:4 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/jetbot/catkin_ws/build_isolated/jetbot_navigation/CMakeFiles/CMakeOutput.log".
See also "/home/jetbot/catkin_ws/build_isolated/jetbot_navigation/CMakeFiles/CMakeError.log".
<== Failed to process package 'jetbot_navigation':
  Command '['/home/jetbot/catkin_ws/devel_isolated/jetbot_gazebo/env.sh', 'cmake', '/home/jetbot/catkin_ws/src/jetbot_diff_drive/jetbot_navigation', '-DCATKIN_DEVEL_PREFIX=/home/jetbot/catkin_ws/devel_isolated/jetbot_navigation', '-DCMAKE_INSTALL_PREFIX=/home/jetbot/catkin_ws/install_isolated', '-G', 'Unix Makefiles']' returned non-zero exit status 1.

Reproduce this error by running:
==> cd /home/jetbot/catkin_ws/build_isolated/jetbot_navigation && /home/jetbot/catkin_ws/devel_isolated/jetbot_gazebo/env.sh cmake /home/jetbot/catkin_ws/src/jetbot_diff_drive/jetbot_navigation -DCATKIN_DEVEL_PREFIX=/home/jetbot/catkin_ws/devel_isolated/jetbot_navigation -DCMAKE_INSTALL_PREFIX=/home/jetbot/catkin_ws/install_isolated -G 'Unix Makefiles'

Command failed, exiting.

**Comment by issaiass** [comment]
Did you follow this steps?

    git clone https://github.com/issaiass/jetbot_diff_drive --recursive
    git clone https://github.com/issaiass/realsense_gazebo_plugin
    git clone https://github.com/issaiass/hector_gazebo_plugins

**Comment by asps946701** [comment]
Yes I do your step in my src folder.
I also try use waveshare jetbot image (18.04) with melodic, but it have same problem.

This is my folder tree
----------------------------------------
jetbot@nano-4gb-jp45:~/workspace/catkin_ws/src$ tree -L 2
.
├── CMakeLists.txt -> /opt/ros/melodic/share/catkin/cmake/toplevel.cmake
├── hector_gazebo_plugins
│   ├── cfg
│   ├── CHANGELOG.rst
│   ├── CMakeLists.txt
│   ├── include
│   ├── package.xml
│   ├── README.md
│   ├── src
│   └── srv
├── jetbot_diff_drive
│   ├── doc
│   ├── jetbot_control
│   ├── jetbot_description
│   ├── jetbot_desktop
│   ├── jetbot_gazebo
│   ├── jetbot_navigation
│   ├── jetbot_robot
│   ├── jetbot_simulator
│   ├── jetbot_slam
│   ├── jetbot_twist_keyboard
│   ├── jetbot_viz
│   └── README.md
├── jetbot_ros
│   ├── CMakeLists.txt
│   ├── gazebo
│   ├── package.xml
│   ├── README.md
│   ├── scripts
│   └── src
├── realsense_gazebo_plugin
│   ├── CMakeLists.txt
│   ├── include
│   ├── package.xml
│   ├── README.md
│   └── src
└── ros_deep_learning
    ├── CMakeLists.txt
    ├── config
    ├── launch
    ├── package.ros1.xml
    ├── package.ros2.xml
    ├── package.xml
    ├── README.md
    ├── ros_deep_learning_nodelets.xml
    └── src

**Comment by issaiass** [comment]
I am using noetic, not melodic, try it to see if there is a problem with it

**Comment by asps946701** [comment]
I try use noetic have same problem.
What is your jetson nano board version ? 
My Jetson nano is NVIDIA A02 4GB (old version). 
 

---------------Version information----------------
-Waveshare jetbot image 18.04 upgrade to 20.04
-ROS version : noetic
-opencv 4.2.0
-python 3.8.10
---------------------------------Folder tree-----------------------------------------------
jetbot@nano-4gb-jp45:~/catkin_ws/src$ tree -L 2
.
├── CMakeLists.txt -> /opt/ros/noetic/share/catkin/cmake/toplevel.cmake
├── hector_gazebo_plugins
│   ├── cfg
│   ├── CHANGELOG.rst
│   ├── CMakeLists.txt
│   ├── include
│   ├── package.xml
│   ├── README.md
│   ├── src
│   └── srv
├── jetbot_diff_drive
│   ├── doc
│   ├── jetbot_control
│   ├── jetbot_description
│   ├── jetbot_desktop
│   ├── jetbot_gazebo
│   ├── jetbot_navigation
│   ├── jetbot_robot
│   ├── jetbot_simulator
│   ├── jetbot_slam
│   ├── jetbot_twist_keyboard
│   ├── jetbot_viz
│   └── README.md
├── jetbot_ros
│   ├── CMakeLists.txt
│   ├── gazebo
│   ├── package.xml
│   ├── README.md
│   ├── scripts
│   └── src
├── realsense_gazebo_plugin
│   ├── CMakeLists.txt
│   ├── include
│   ├── package.xml
│   ├── README.md
│   └── src
└── ros_deep_learning
    ├── CMakeLists.txt
    ├── config
    ├── launch
    ├── package.ros1.xml
    ├── package.ros2.xml
    ├── package.xml
    ├── README.md
    ├── ros_deep_learning_nodelets.xml
    └── src

28 directories, 18 files

-------------------------jetbot_navigation catkin message----------------------
=> Processing catkin package: 'jetbot_navigation'
==> Building with env: '/home/jetbot/catkin_ws/devel_isolated/jetbot_gazebo/env.sh'
==> cmake /home/jetbot/catkin_ws/src/jetbot_diff_drive/jetbot_navigation -DCATKIN_DEVEL_PREFIX=/home/jetbot/catkin_ws/devel_isolated/jetbot_navigation -DCMAKE_INSTALL_PREFIX=/home/jetbot/catkin_ws/install_isolated -G Unix Makefiles in '/home/jetbot/catkin_ws/build_isolated/jetbot_navigation'
-- Using CATKIN_DEVEL_PREFIX: /home/jetbot/catkin_ws/devel_isolated/jetbot_navigation
-- Using CMAKE_PREFIX_PATH: /home/jetbot/catkin_ws/devel_isolated/jetbot_gazebo;/home/jetbot/catkin_ws/devel_isolated/jetbot_desktop;/home/jetbot/catkin_ws/devel_isolated/jetbot_description;/home/jetbot/catkin_ws/devel_isolated/jetbot_control;/home/jetbot/catkin_ws/devel_isolated/hector_gazebo_plugins;/home/jetbot/catkin_ws/devel;/opt/ros/noetic
-- This workspace overlays: /home/jetbot/catkin_ws/devel_isolated/jetbot_gazebo;/home/jetbot/catkin_ws/devel_isolated/jetbot_desktop;/home/jetbot/catkin_ws/devel_isolated/jetbot_description;/home/jetbot/catkin_ws/devel_isolated/jetbot_control;/home/jetbot/catkin_ws/devel_isolated/hector_gazebo_plugins;/home/jetbot/catkin_ws/devel;/opt/ros/noetic
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Using Debian Python package layout
-- Using empy: /usr/lib/python3/dist-packages/em.py
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/jetbot/catkin_ws/build_isolated/jetbot_navigation/test_results
-- Forcing gtest/gmock from source, though one was otherwise available.
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python3 (found version "3.8.10") 
-- Using Python nosetests: /usr/bin/nosetests3
-- catkin 0.8.10
-- BUILD_SHARED_LIBS is on
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Could NOT find jetbot_viz (missing: jetbot_viz_DIR)
-- Could not find the required component 'jetbot_viz'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "jetbot_viz" with
  any of the following names:

    jetbot_vizConfig.cmake
    jetbot_viz-config.cmake

  Add the installation prefix of "jetbot_viz" to CMAKE_PREFIX_PATH or set
  "jetbot_viz_DIR" to a directory containing one of the above files.  If
  "jetbot_viz" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:4 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/jetbot/catkin_ws/build_isolated/jetbot_navigation/CMakeFiles/CMakeOutput.log".
See also "/home/jetbot/catkin_ws/build_isolated/jetbot_navigation/CMakeFiles/CMakeError.log".
<== Failed to process package 'jetbot_navigation': 
  Command '['/home/jetbot/catkin_ws/devel_isolated/jetbot_gazebo/env.sh', 'cmake', '/home/jetbot/catkin_ws/src/jetbot_diff_drive/jetbot_navigation', '-DCATKIN_DEVEL_PREFIX=/home/jetbot/catkin_ws/devel_isolated/jetbot_navigation', '-DCMAKE_INSTALL_PREFIX=/home/jetbot/catkin_ws/install_isolated', '-G', 'Unix Makefiles']' returned non-zero exit status 1.

Reproduce this error by running:
==> cd /home/jetbot/catkin_ws/build_isolated/jetbot_navigation && /home/jetbot/catkin_ws/devel_isolated/jetbot_gazebo/env.sh cmake /home/jetbot/catkin_ws/src/jetbot_diff_drive/jetbot_navigation -DCATKIN_DEVEL_PREFIX=/home/jetbot/catkin_ws/devel_isolated/jetbot_navigation -DCMAKE_INSTALL_PREFIX=/home/jetbot/catkin_ws/install_isolated -G 'Unix Makefiles'

Command failed, exiting.

**Comment by issaiass** [comment]
No. I am using gazebo, not the jetson nor raspberry or other boards.

**Comment by asps946701** [comment]
I have misunderstand. 
I will try it by gazebo
Thanks you very much!

**Comment by asps946701** [comment]
I try use desktop to do it but it also cannot find jetbot_viz.
I use 'rospack find' can find jetbot_viz , but 'catkin_make' say could not find.

-----------------------------------------------------------

smg@smg:~/catkin_ws$ rospack find jetbot_viz 
/home/smg/catkin_ws/src/jetbot_diff_drive/jetbot_viz

 -----------------------------------------------------------

ROS version : noetic
ubuntu : 20.04

-----------------------------------------------------------

-- Could NOT find jetbot_viz (missing: jetbot_viz_DIR)
-- Could not find the required component 'jetbot_viz'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "jetbot_viz" with
  any of the following names:

    jetbot_vizConfig.cmake
    jetbot_viz-config.cmake

  Add the installation prefix of "jetbot_viz" to CMAKE_PREFIX_PATH or set
  "jetbot_viz_DIR" to a directory containing one of the above files.  If
  "jetbot_viz" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:4 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/smg/catkin_ws/build_isolated/jetbot_navigation/CMakeFiles/CMakeOutput.log".
See also "/home/smg/catkin_ws/build_isolated/jetbot_navigation/CMakeFiles/CMakeError.log".
<== Failed to process package 'jetbot_navigation': 
  Command '['/home/smg/catkin_ws/devel_isolated/jetbot_gazebo/env.sh', 'cmake', '/home/smg/catkin_ws/src/jetbot_diff_drive/jetbot_navigation', '-DCATKIN_DEVEL_PREFIX=/home/smg/catkin_ws/devel_isolated/jetbot_navigation', '-DCMAKE_INSTALL_PREFIX=/home/smg/catkin_ws/install_isolated', '-G', 'Unix Makefiles']' returned non-zero exit status 1.

Reproduce this error by running:
==> cd /home/smg/catkin_ws/build_isolated/jetbot_navigation && /home/smg/catkin_ws/devel_isolated/jetbot_gazebo/env.sh cmake /home/smg/catkin_ws/src/jetbot_diff_drive/jetbot_navigation -DCATKIN_DEVEL_PREFIX=/home/smg/catkin_ws/devel_isolated/jetbot_navigation -DCMAKE_INSTALL_PREFIX=/home/smg/catkin_ws/install_isolated -G 'Unix Makefiles'

Command failed, exiting.

**Comment by issaiass** [comment]
Try to build each package separately.

That build errors doesn't make sense for me because you have jetbot_viz.

**Comment by issaiass** [comment]
First do a catkin_make for only one package

    catkin_make --only-pkg-with-deps <target_package>

Next make catkin see all packages

    catkin_make -DCATKIN_WHITELIST_PACKAGES=""

**Comment by asps946701** [comment]
I try to use catkin_make --only-pkg-with-deps <target_package> to fixed error by error message. 

Now catkin_make -DCATKIN_WHITELIST_PACKAGES="" & catkin_make with no error message.

Thanks you very much

--------------my note------------------------
**jetbot_robot / jetbot_desktop /jetbot_simulator. …..Done**	
	This workspace contains non-catkin packages in it, and catkin cannot build
  	a non-homogeneous workspace without isolation.  Try the
  	'catkin_make_isolated' command instead.	
-According 2.4 Metapackages https://wiki.ros.org/catkin/package.xml#Metapackages  format ,I try delete blank row and change sequence(like jetbot_robot) …….solved
	

**jetbot_slam...….Done**
	- '/home/smg/catkin_ws/src/jetbot_diff_drive/jetbot_slam/launch/cartographer_demo.launch' was not found
	- Change to use other launch file.….solved 	

**jetbot_navigation….Done**
	-Unknown CMake command "roslaunch_add_file_check" . …...Try #3  ….solved 
        -Could not found map-sever & move-base. …..install map-sever & move-base  …..solved 

**jetbot_twist_keyboard …..Done**
	- catkin_package_xml() package name 'jetbot_twist_keyboard' in
 	 '/home/smg/catkin_ws/src/jetbot_diff_drive/jetbot_twist_keyboard/package.xml'
  	does not match current PROJECT_NAME 'teleop_twist_keyboard'.  You must call
 	 project() with the same package name before.

       - CmakeLists.txt -> project(teleop_twist_keyboard →project(jetbot_twist_keyboard)

**hector_gazebo_plugins….Done
realsense_gazebo_plugin….Done
jetbot_viz….Done
jetbot_control….Done
jetbot_description….Done
jetbot_gazebo….Done**
